### ISSUE TITLE
MinigetError: Status code: 404

### ISSUE THREAD

**Issue by Gomez0015** [RemyK888/discord-music-system#15]
When using the play <link> command I get the following error:

2021-06-25T11:43:47.771719+00:00 app[worker.1]: MinigetError: Status code: 404
2021-06-25T11:43:47.771777+00:00 app[worker.1]:     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:210:27)
2021-06-25T11:43:47.771778+00:00 app[worker.1]:     at Object.onceWrapper (events.js:482:26)
2021-06-25T11:43:47.771778+00:00 app[worker.1]:     at ClientRequest.emit (events.js:375:28)
2021-06-25T11:43:47.771779+00:00 app[worker.1]:     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
2021-06-25T11:43:47.771779+00:00 app[worker.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
2021-06-25T11:43:47.771780+00:00 app[worker.1]:     at TLSSocket.socketOnData (_http_client.js:515:22)
2021-06-25T11:43:47.771780+00:00 app[worker.1]:     at TLSSocket.emit (events.js:375:28)
2021-06-25T11:43:47.771781+00:00 app[worker.1]:     at addChunk (internal/streams/readable.js:290:12)
2021-06-25T11:43:47.771781+00:00 app[worker.1]:     at readableAddChunk (internal/streams/readable.js:265:9)
2021-06-25T11:43:47.771782+00:00 app[worker.1]:     at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
2021-06-25T11:43:47.771782+00:00 app[worker.1]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
2021-06-25T11:43:47.771782+00:00 app[worker.1]:   statusCode: 404
2021-06-25T11:43:47.771783+00:00 app[worker.1]: }

**Comment by Scarner56** [comment]
youtube has updated its API, you will continue to see this error until new update to ytdl-core module

**Comment by Gomez0015** [comment]
Okay so you mean like updating my api key and such?

**Comment by Scarner56** [comment]
no no you have to wait but you can change it if you want (I don't think it will work)

**Comment by Gomez0015** [comment]
Oh Okay so basically I cannot do anything about it, just have to wait. And how long do you think it will take until they update the ytdl core module

**Comment by Gomez0015** [comment]
Thanks for all the info and quick response btw

**Comment by Scarner56** [comment]
I have no idea

**Comment by Scarner56** [comment]
not at all :)

**Comment by Scarner56** [comment]
A new version of the ytld-core module is out. Update

**Comment by RemyK888** [comment]
Thanks for the comment, i think i'll update the package tomorrow !
