### ISSUE TITLE
Error playing music

### ISSUE THREAD

**Issue by ChrisTVH** [RemyK888/discord-music-system#2]
```
(node:154453) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:122:11)
    at Url.parse (url.js:159:3)
    at urlParse (url.js:154:13)
    at Url.resolve (url.js:667:29)
    at Object.urlResolve [as resolve] (url.js:663:40)
    at exports.getInfo (/home/projects/pwcommunity/bot-developers/pixelworld/BOT/node_modules/ytdl-core/lib/info.js:227:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Map.getOrSet (/home/projects/pwcommunity/bot-developers/pixelworld/BOT/node_modules/ytdl-core/lib/cache.js:24:19)
    at async MusicBot.playQuery (/home/projects/pwcommunity/bot-developers/pixelworld/BOT/node_modules/discord-music-system-es/src/MusicBot.js:432:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:154453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:154453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RemyK888** [comment]
Which version of the package do you use ? @ChrisTVH

**Comment by ChrisTVH** [comment]
3.0.1 I recently fixed that it has been updated, sorry for the inconvenience, if the problem persists, I will report it again

**Comment by ChrisTVH** [comment]
I already tried it and it works well, it would be good if this
package could be changed between languages by configuring the same example spanish.json, english.json, french.json if they are going to implement it here I leave my translation into Spanish
[language.zip](https://github.com/RemyK888/discord-music-system/files/5447394/language.zip)

**Comment by RemyK888** [comment]
Thanks a lot for this Spanish translation^^. Can I close this issue if you have no more problems ?

**Comment by ChrisTVH** [comment]
If you can close, if I have a problem I will report it
